### PR TITLE
Added evaluate_postfix.cpp

### PR DESCRIPTION
**Pull request by Naveen28101**

### CODE REVIEW

**Comment by 1Alisha** [comment]
Don't forget to star this repository 
keep contributing
Thanks:)

**Comment by AKG1301** [comment]
please assign this task to me

**Comment by AKG1301** [comment]
completed

**Comment by AKG1301** [comment]
completed 
https://github.com/1Alisha/HACKTOBERFEST-22/pull/54#issue-1408125541 
second file("binary search.py file")

**Comment by AKG1301** [comment]
correction done.
https://github.com/1Alisha/HACKTOBERFEST-22/pull/60#issue-1408243297

**Pull request merged**
