### PR TITLE
check loop present in ll.cpp and middle of the loop.cpp file created

### PR DESCRIPTION
**Pull request by AKG1301**

### CODE REVIEW

**Comment by AKG1301** [comment]
Please accept this pr

**Comment by AKG1301** [comment]
IMG_20221014_214239
Why it shows not accepted?

**Comment by AKG1301** [comment]
@1Alisha please check this pr

**Comment by AKG1301** [comment]
@1Alisha please check this pr also.

**Comment by AKG1301** [comment]
@1Alisha please check this pr.

**Comment by 1Alisha** [comment]
@AKG1301 
Please Don't forget to follow and star this repository
Keep Contributing
Thanks:)

**Pull request merged**
